settings:
  title: 'Gooner Network Status Page'
  url: 'https://ops-status.goonernet.work' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
  
  - id: jerryflynn-demondad-xyz
    name: Jerry Flynn 
    description: 'Jerry Flynn the Jellyfin'
    url: 'https://jerryflynn.demondad.xyz/health'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: Argo-Tunnel-1
    name: Cletus 
    description: 'Argo Tunnel 1'
    url: 'https://at1.goonernet.work'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: Argo-Tunnel-2
    name: Kub 
    description: 'Argo Tunnel 2'
    url: 'https://at2.goonernet.work'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: Argo-Tunnel-3
    name: SixtyFour 
    description: 'Argo Tunnel 3'
    url: 'https://at3.goonernet.work'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: Argo-Tunnel-4
    name: Neon 
    description: 'Argo Tunnel 4'
    url: 'https://at4.goonernet.work'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
